version: "3.9"
services:
  web:
    build: ./ComposeTest.API/
    command: "/bin/bash ./entrypoint.sh"
    ports:
      - "8080:5000"
    volumes:
      - ./ComposeTest.API/:/app
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
